---
  - name: Ensure the Mono GPG key has been imported
    apt_key:
      state: present
      url: "{{ webmin_ppa_key }}"

  - name: Add apt repositories.
    apt_repository:
      repo: "deb {{ item }}"
      state: present
    with_items:
      - 'http://download.webmin.com/download/repository sarge contrib'
      - 'http://webmin.mirror.somersettechsolutions.co.uk/repository sarge contrib'

  - name: Update APT Cache
    apt:
      update_cache: yes

  - name: Install webmin.
    apt:
      name: "webmin={{ webmin_version }}"
      state: present
      force: yes



