---
- name: Install the RPM.
  yum:
    name: "http://prdownloads.sourceforge.net/webadmin/webmin-{{ webmin_version }}-1.noarch.rpm"
    state: present
  sudo: yes

- name: Install webmin.
  yum:
    name: webmin
    state: present
  sudo: yes
